"""
Idea.py

The Idea class represents an idea generated by the BrainstormBoost application. 
Each idea is characterized by its title, a description, and a number of votes it has received. 
The class provides methods to increment or decrement the vote count of an idea.
"""

class Idea:
    # Constructor
    def __init__(self, title='', description='', votes=0):
        self.title = title
        self.description = description
        self.votes = votes

    def __str__(self):
        return f"{self.title}\n{self.description}\n"

    # Get, Add and Reduce vote counter
    def AddVote(self):
        self.votes += 1

    def RemoveVote(self):
        if (self.votes <= 0):
            pass
        else:
            self.votes -= 1

if __name__ == '__main__':
    # Test Idea class
    print("\nTesting Idea class...")
    idea1 = Idea("AI for Healthcare", "Using AI to predict diseases and help doctors.", 0)
    print("Idea Title: ", idea1.title)
    print("Idea Description: ", idea1.description)
    print("Idea Votes: ", idea1.votes)

    idea1.AddVote()
    print("After adding a vote:")
    print("Idea Votes: ", idea1.votes)

    idea1.RemoveVote()
    print("After removing a vote:")
    print("Idea Votes: ", idea1.votes)
